### ISSUE TITLE
Arduino

### ISSUE THREAD

**Issue by rosalindmc** [rosalindmc/Final#2]
int sensorValue;
int inputPin = 0;

void setup() 
{
  Serial.begin(9600);
}

void loop() 
{
  sensorValue = round(analogRead(inputPin)/4) ;
  Serial.println(sensorValue);
  delay(5);
}

**Comment by Shraddha96** [comment]
What is the problem?

**Comment by rosalindmc** [comment]
are teacher wanted us to post code for a class but I didnt know how so I
posted everything in issues.  I'll take it down.
